name: Run basic features tests on CPU with empty SD model

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sd-webui-comfyui
        uses: actions/checkout@v3

      - name: Checkout stable-diffusion-webui
        uses: actions/checkout@v3
        with:
          repository: 'AUTOMATIC1111/stable-diffusion-webui'
          path: 'stable-diffusion-webui'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: pip
          cache-dependency-path: |
            **/requirements*txt
            stable-diffusion-webui/launch.py

      - name: Install test dependencies
        run: |
          pip install -r requirements.txt -r requirements-test.txt
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_PROGRESS_BAR: "off"

      - name: Setup environment
        run: |
          cd stable-diffusion-webui
          python launch.py --skip-torch-cuda-test --exit
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_PROGRESS_BAR: "off"
          TORCH_INDEX_URL: https://download.pytorch.org/whl/cpu
          WEBUI_LAUNCH_LIVE_OUTPUT: "1"
          PYTHONUNBUFFERED: "1"

      - name: Run tests
        run: |
          python -m pytest -vv --junitxml=tests/results.xml tests
